grails-plugins/grails-spring-security-core

src/groovy/grails/plugin/springsecurity/web/authentication/rememberme/GormPersistentTokenRepository.groovy

See https://jira.grails.org/browse/GPSPRINGSECURITYCORE-309
After updating from Grails 2.3.11 to Grails 2.4.4 I was getting the following stacktrace relating to the persistent login lookup.
```
org.springframework.dao.DataAccessResourceFailureException: Could not obtain current Hibernate Session; nested exception is org.hibernate.HibernateException: No Session found for current thread
at org.codehaus.groovy.grails.orm.hibernate.GrailsHibernateTemplate.getSession(GrailsHibernateTemplate.java:210)
at org.codehaus.groovy.grails.orm.hibernate.GrailsHibernateTemplate.doExecute(GrailsHibernateTemplate.java:166)
at org.codehaus.groovy.grails.orm.hibernate.GrailsHibernateTemplate.get(GrailsHibernateTemplate.java:239)
at org.codehaus.groovy.grails.orm.hibernate.HibernateGormStaticApi.doGetInstance( …
```

GPSPRINGSECURITYCORE-309 GormPersistentTokenRepository should use a transaction when retrieving persistent login

---

src/docs/guide/requestMappings/securedAnnotations.gdoc

This information is present in the what's new in v2 section but not in the documentation itself. This was pointed out on the Grails IRC channel as confusing.

Added information about closures within @Secured

---

src/java/grails/plugin/springsecurity/SpringSecurityUtils.java
test/unit/grails/plugin/springsecurity/SpringSecurityUtilsTests.groovy

Fix for isAjax, saved requests. It should be consistent with non-saved requests!

https://jira.grails.org/browse/GPSPRINGSECURITYCORE-197

---

grails-app/controllers/grails/plugin/springsecurity/LoginController.groovy

…This is a fix to make it compatible with Grails 3 and return the correct status code for UNAUTHORIZED.

authAjax currently returns a status 200 with /authAjax using Grails 3

---

.gitignore
src/docs/hierarchicalRoles.adoc

A call to `grails.plugin.springsecurity.SpringSecurityService#reloadDBRoleHierarchy` is needed to use new/updated/deleted `RoleHierarchyEntity` instances.

Added documentation about `RoleHierarchyEntry` updates

---

src/main/groovy/grails/plugin/springsecurity/access/vote/AuthenticatedVetoableDecisionManager.groovy
src/test/groovy/grails/plugin/springsecurity/access/vote/AuthenticatedVetoableDecisionManagerSpec.groovy

Currently voters are executed even if they don't support the supplied security context object. 
This should be checked. I've created a security plugin which uses this technique and it fails now.

Unsupported voters should be skipped

---

grails-app/conf/DefaultSecurityConfig.groovy
src/docs/passwords/hashing.adoc

See #498
* Switch default `bcrypt` value based on `Environment.current`
* Updated doc

bcrypt lower values for tests

---

grails-app/taglib/grails/plugin/springsecurity/SecurityTagLib.groovy

This brings `<sec:access>` attribute parsing in-line with `<sec:link>` in that it passes all valid attributes to the `createLink` method.
Existing behaviors retained:
* unspecified method defaults to 'GET'
* if `url` is specified it is still processed, but the `DefaultLinkGenerator` prints it out unmodified (so section 6.1.11 Example 37 should still work)
This shouldn't break any existing apps that rely on any of the above behaviors.
Addresses https://github.com/grails-plugins/grails-spring-security-core/issues/486

Support all link attributes for sec:access tag

---

plugin/src/docs/examples.adoc
plugin/src/docs/index.adoc

The purpose of this is to make users aware of the example apps and provide another avenue for learning.
Example apps are listed at https://github.com/grails-spring-security-samples

Issue #519: Create a new sample section in the docs with links to examples

---

integration-test-app/src/integration-test/groovy/grails/plugin/springsecurity/SpringSecurityUtilsIntegrationSpec.groovy
plugin/grails-app/conf/DefaultSecurityConfig.groovy
plugin/src/docs/miscProperties.adoc

This will make using the plugin in new threads easier.
Changes include:
- modifying contents of `DefaultSecurityConfig` from `SecurityContextHolder.MODE_THREADLOCAL` to `SecurityContextHolder.MODE_INHERITABLETHREADLOCAL`
- Fixed tests which broke after the above mentioned modification
This PR is for issue [#516](https://github.com/grails-plugins/grails-spring-security-core/issues/516) 
Per @sdelamo 
> The tests which fail: 
>
> https://github.com/grails-plugins/grails-spring-security-core/blob/master/integration-test-app/src/integration-test/groovy/grails/plugin/springsecurity/SpringSecurityUtilsIntegrationSpec.groovy#L159
>
> https://github.com/grails-plugins/grails-spring-security-core/blob/master/integration-test-app/src/integration-test/groovy/grails/plugin/springsecurity/SpringSecurit …

Issue #516: Change default SecurityContextHolderStrategy to MODE_INHERITABLETHREADLOCAL 

---

plugin/src/main/groovy/grails/plugin/springsecurity/SpringSecurityCoreGrailsPlugin.groovy

I left the `println`s in place because they are there so that developers may see the the current state of the `spring-security-core` plugin when the app starts, regardless of whether they've configured the correct log level.
I've modified all but one of the startup messages to utilize log level `info`.
This fixes issue #521

Issue #521: Informational messages are logged with level "WARN"

---

plugin/src/docs/filters.adoc

Modified the documentation to clarify which filter chain is being modified as recommended in the following comment from Issue #548 :
>I think an additional note/comment in the documentation would be great, that the term filter chain in this context refers to the spring security filter chain. Usually when I hear the term I instinctively think of the application servers filter chain first.

Issue 548: modify documentation to clarify which filter chain is being modified

---

ISSUE_TEMPLATE.md

This will be great for prompting users to supply the information required to reproduce and fix the issue.
Example issue template: https://github.com/grails/grails-data-mapping/blob/master/ISSUE_TEMPLATE.md

Issue 546: Create an issue template similar to what is used in the grails-data-mapping plugin

---

build.gradle

Upgrade to Spring Security 4.1.5.RELEASE.
See https://pivotal.io/security/cve-2018-1199.

Mitigate CVE-2018-1199

---

functional-test-app/build.gradle
functional-test-app/grails-app/conf/spring/resources.groovy
functional-test-app/grails-app/init/functional/test/app/BootStrap.groovy
functional-test-app/src/integration-test/groovy/specs/CustomFilterRegistrationSpec.groovy
functional-test-app/src/main/groovy/com/testapp/MaintenanceModeFilter.groovy
gradle/testVerbose.gradle
integration-test-app/build.gradle
misc-functional-test-app/grails-spring-security-group/build.gradle
misc-functional-test-app/grails-spring-security-hierarchical-roles/build.gradle
plugin/src/main/groovy/grails/plugin/springsecurity/SpringSecurityUtils.groovy
plugin/src/test/groovy/grails/plugin/springsecurity/SpringSecurityUtilsSpec.groovy
travis-build.sh

This bug occurs when a custom filter is added by calling `SpringSecurityUtils.clientRegisterFilter` in `BootStrap.groovy`.
The `clientRegisterFilter` method calls `mergeFilterChains` which properly handles excluded filters, but does not address the situation where a chainMap pattern is associated with no filters, i.e.:
```
grails.plugin.springsecurity.filterChain.chainMap = [
[pattern: '/assets/**',      filters: 'none']
]
```
Everything works as expected for non-custom loaded filters because `buildFilterChains` is called for all default chains and properly handles chain maps with `filters: 'none'`.
This fix modifies `clientRegisterFilter` to take `filters: 'none''` into account.
---
This PR is for Issue #503

Issue #503: Registering filter breaks the chain map

---

plugin/src/docs/requestMappings.adoc

The example references ROLE_ADMIN, but the descriptive text accidentally referred to ROLE_USER.

Change ROLE_USER to ROLE_ADMIN

---

integration-test-app/src/integration-test/groovy/grails/plugin/springsecurity/SecurityTagLibSpec.groovy
plugin/grails-app/taglib/grails/plugin/springsecurity/SecurityTagLib.groovy
plugin/src/docs/helperClasses/securityTagLib.adoc

In the case that a user doesn't have access to a particular link, allow the text that would have been linked to be displayed.

Add fallback attribute to link tag

---

functional-test-app/build.gradle
functional-test-app/gradle.properties
integration-test-app/build.gradle
integration-test-app/gradle.properties
misc-functional-test-app/grails-spring-security-group/build.gradle
misc-functional-test-app/grails-spring-security-group/gradle.properties
misc-functional-test-app/grails-spring-security-hierarchical-roles/build.gradle
misc-functional-test-app/grails-spring-security-hierarchical-roles/gradle.properties
plugin/src/docs/code/s2-quickstart-requestmap/gradle.properties
plugin/src/docs/code/s2-quickstart-rolegroup/gradle.properties
plugin/src/docs/code/s2-quickstart/gradle.properties
plugin/src/main/scripts/s2-quickstart.groovy

When a new grails 4 app is created, the GORM version is set in the `gradle.properties` file as follows:
```
gorm.version=7.0.1.RELEASE
```
This is different from pre grails 4 apps where the GORM version was set like the following:
```
gormVersion=6.1.9.RELEASE
```
Notice how the key used to define the GORM version has changed.
I've modified the `s2-quickstart` script as well as project files to support the new way of reference GORM version in grails 4 apps.
This PR is for issue #575

Issue-575: UserPasswordEncoderListener not generated by s2-quickstart script in Grails 4

---

plugin/src/docs/requestMappings.adoc
plugin/src/docs/requestMappings/configGroovyMap.adoc
plugin/src/docs/requestMappings/requestmapInstances.adoc
plugin/src/docs/switchUser.adoc

This is a temporary fix to address the concerns surrounding the use of `isFullyAuthenticated()`.
There will be a future PR which addresses the root cause within the code itself.
This PR is for issue #574

Issue-574: isFullyAuthenticated() vs IS_AUTHENTICATED_FULLY

---

plugin/src/main/groovy/grails/plugin/springsecurity/ReflectionUtils.groovy
plugin/src/test/groovy/grails/plugin/springsecurity/ReflectionUtilsSpec.groovy

Fix ReflectionUtils.findFilterChainNames when config values come from .properties file and need explicit boolean conversion.

Fix ReflectionUtils.findFilterChainNames

---

plugin/src/main/groovy/grails/plugin/springsecurity/SpringSecurityCoreGrailsPlugin.groovy
plugin/src/main/groovy/grails/plugin/springsecurity/web/authentication/AjaxAwareAuthenticationFailureHandler.groovy

This was a super minor bug, but it really grated me every time I saw it...
Adds an alternatively named bean setter that serves the exact same purpose, but will avoid tripping the GenericTypeAwarePropertyDescriptor "ambiguous property" warning by default. Also changes the default config names so spring will utilize the new setter by default.
Kept the original around so as to not break any custom defined AjaxAwareAuthenticationFailureHandler.
Fixes #459

Use unambiguous setter method name
